### ISSUE TITLE
PLATFORM_NOT_FOUND_KHR error

### ISSUE THREAD

**Issue by MaestSi** [swarris/Pacasus#20]
Hi,
I seem to have a similar issue to the one reported [here](https://github.com/swarris/Pacasus/issues/17). I am running on a server with Intel CPUs with Ubuntu 20.04.1.
This is the content of the current conda environment:

```
# packages in environment at /home/simone/miniconda3/envs/Pacasus_env:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0    pypi
biopython                 1.78                     pypi_0    pypi
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20                py38_0    anaconda
decorator                 4.4.2                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
mako                      1.1.4                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    anaconda
numpy                     1.20.1                   pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0    anaconda
pip                       20.2.4                   py38_0    anaconda
pyopencl                  2021.1.1                 pypi_0    pypi
python                    3.8.5                h7579374_1    anaconda
pytools                   2021.1                   pypi_0    pypi
readline                  8.0                  h7b6447c_0    anaconda
setuptools                50.3.0           py38hb0f4dca_1    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
wheel                     0.35.1                     py_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
```

This is the command I ran:

`python pacasus.py --device_type=CPU --platform_name=Intel --framework=opencl <file.fastq.gz>`

And this is the error I got:

```
INFO - Initializing application...
DEBUG - Initializing Score...
DEBUG - Initializing score finished.
DEBUG - Initializing DnaRnaScore...
DEBUG - Creating matrix with parameters:
                match_score: 3,
                mismatch_score: -4,
                gap_score: -3.0,
                other_score: -1,
                any_score: 0
DEBUG - Initializing DnaRnaScore finished.
INFO - Application initialized.
INFO - Setting program...
DEBUG - Initializing aligner...
DEBUG - Initializing hitlist...
DEBUG - Initializing hitlist OK.
DEBUG - Setting SW...
DEBUG - Using OpenCL CPU implementation
DEBUG - Initializing SmithWaterman.
INFO - No gap extension penalty detected: using original PaSWAS scoring algorithm
ERROR - clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
Traceback (most recent call last):
  File "pacasus.py", line 13, in <module>
    ppw.run()
  File "/home/simone/software/Pacasus/pacasus/pacasusall.py", line 106, in run
    self._set_program()
  File "/home/simone/software/Pacasus/pacasus/pacasusall.py", line 82, in _set_program
    self.program = Palindrome(self.logger, self.score, self.settings)
  File "/home/simone/software/Pacasus/pacasus/Core/Programs.py", line 13, in __init__
    Aligner.__init__(self, logger, score, settings)
  File "/home/simone/software/Pacasus/pypaswas/pyPaSWAS/Core/Programs.py", line 44, in __init__
    self.smith_waterman = SmithWatermanCPU(self.logger, self.score, settings)
  File "/home/simone/software/Pacasus/pypaswas/pyPaSWAS/Core/SmithWatermanOcl.py", line 348, in __init__
    SmithWatermanOcl.__init__(self, logger, score, settings)
  File "/home/simone/software/Pacasus/pypaswas/pyPaSWAS/Core/SmithWatermanOcl.py", line 38, in __init__
    self._set_platform(self.settings.platform_name)
  File "/home/simone/software/Pacasus/pypaswas/pyPaSWAS/Core/SmithWatermanOcl.py", line 91, in _set_platform
    for platform in cl.get_platforms():
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
```

Is there anything I could try out to fix it? Based on the referenced issue it looks like there isn't much I could do...
Thanks,
Simone

**Comment by swarris** [comment]
Hi Simone,

Sorry for the late reply. The reasons why you get this message could be many, but the message itself states that there is no OpenCL-capable device found. To varify, did you:
- install the OpenCL driver on your system?
- run the example found at https://documen.tician.de/pyopencl/ ?

If the latter works, the problem might be related to your conda-environment.
Best,
Sven

**Comment by MaestSi** [comment]
I think I have an error with pycuda and opencl, I tried to repeat the installation from scratch and the command:
`pip install pyCuda pyOpenCL`
gives me errors.
So thank you for your support. You can close the issue if you want.
Simone
